// Generated by CoffeeScript 1.10.0
(function() {
  var commander, fs, getCommand, getConfig, getPath, getTemplate, getTemplateForWeekend, getTitle, moment, path;

  fs = require('fs-extra');

  path = require('path');

  commander = require('commander-b');

  moment = require('moment');

  getCommand = function() {
    var program;
    program = commander('bbn');
    program.version(require('../package.json').version);
    program.command('new', 'create a new post').option('-d, --date <date>').option('-w, --weekend').action(function(options) {
      var config, data, date, file, ts;
      if (options == null) {
        options = {};
      }
      config = getConfig();
      options.directory = config.directory || '/home/bouzuya/blog.bouzuya.net';
      ts = options.date ? options.date + 'T23:59:59+09:00' : null;
      date = moment.apply(null, ts != null ? [ts, 'YYYY-MM-DDThh:mm:ssZ'] : []);
      file = getPath(options.directory, date.format('YYYY-MM-DD'));
      if (fs.existsSync(file)) {
        console.error("the post " + file + " already exists");
        return 1;
      } else {
        data = getTemplate(date, options);
        fs.outputFileSync(file, data, {
          encoding: 'utf8'
        });
        console.log("create a new post " + file);
        return 0;
      }
    });
    return program;
  };

  getConfig = function() {
    var configFile;
    configFile = path.join(process.env.HOME, '.bbn.json');
    if (fs.existsSync(configFile)) {
      return require(configFile);
    } else {
      return {};
    }
  };

  getPath = function(dir, date) {
    var _, m, ref, y;
    ref = date.split('-'), y = ref[0], m = ref[1], _ = ref[2];
    return path.join(dir, 'data', y, m, date + '-diary.md');
  };

  getTemplate = function(m, options) {
    return "---\nlayout: post\npubdate: \"" + (m.format()) + "\"\ntitle: ''\ntags: ['']\nminutes:\npagetype: posts\n---\n\n" + (options.weekend ? getTemplateForWeekend(m, options) : '');
  };

  getTemplateForWeekend = function(m, options) {
    var posts;
    posts = [1, 2, 3, 4, 5, 6, 7].map(function(i) {
      return moment(m).subtract(i, 'days').format('YYYY-MM-DD');
    }).map(function(date) {
      return {
        date: date,
        title: getTitle(options.directory, date),
        url: "http://blog.bouzuya.net/" + (date.replace(/-/g, '/')) + "/"
      };
    });
    return "# 今週のふりかえり\n\n" + (posts.map(function(i) {
      return "- [" + i.date + " " + i.title + "][" + i.date + "]";
    }).join('\n'));
  };

  getTitle = function(dir, date) {
    var data, title;
    data = fs.readFileSync(getPath(dir, date), {
      encoding: 'utf8'
    });
    title = data.match(/^title: '?(.*)$/m)[1];
    if (title[title.length - 1] === '\'') {
      return title.slice(0, -1);
    } else {
      return title;
    }
  };

  module.exports = function() {
    var command;
    command = getCommand();
    return command.execute();
  };

}).call(this);
